### ISSUE TITLE
CityGML2CityJSON: SolitaryVegetationObject(s) in a CityObjectGroup are not converted

### ISSUE THREAD

**Issue by kkimmy** [citygml4j/citygml4j#12]
In citygml4j/samples/cityjson/citygml2cityjson/SimpleConverter.java, SolitaryVegetationObject(s) in a CityObjectGroup are not converted. I tested the code with sample dataset "Part-1-Terrain-WaterBody-Vegetation-V2.gml". The dataset has 15 vegetation objects but upon converting it to CityJSON, only one vegetation object (GML ID: "GMLID_SO092422_3593_9527") is written to CityJSON file.

**Comment by clausnagel** [comment]
Just tested with the master branch and I get 15 trees. Please build the library from the master branch and test again (see [how to build citygml4j](https://github.com/citygml4j/citygml4j#building)). Let me know whether it works or you need support.

**Comment by clausnagel** [comment]
closing this issue due to no response. feel free to reopen if the issue still exists
