### ISSUE TITLE
Cityjson Lod4 Marshaller

### ISSUE THREAD

**Issue by choiyoonho2** [citygml4j/citygml4j#15]
![lod](https://user-images.githubusercontent.com/12508396/38222904-b7d14af2-3722-11e8-86df-7ab8daa29c70.JPG)
Hi. I'm using citygml4j library. 
I am in the process of converting the citygml file to cityjson and extracting the data.
Why is there no processing for LOD4 in cityjson marshallers? Is it going to be developed? 
What is the reason?

**Comment by clausnagel** [comment]
CityJSON does not support LOD4 features and geometries at the moment (see here: http://www.cityjson.org/en/0.5/citygmlsupport/). So this is not a citygml4j issue.

Feel free to post an issue on the [CityJSON GitHub page](https://github.com/tudelft3d/cityjson).
