### ISSUE TITLE
does citygml 4j support lidar data?

### ISSUE THREAD

**Issue by PURNIMA1298** [citygml4j/citygml4j#17]
does this program support lidar data as input for creating lod2 citygml models?

**Comment by clausnagel** [comment]
citygml4j is a programming library that supports you in parsing/writing CityGML datasets. It is not a product to generate CityGML data from GIS raw data.

If lidar data is your input, you may be interested in the software [BuildingReconstruction](https://www.virtualcitysystems.de/en/products/buildingreconstruction) from [virtualcitySYSTEMS](https://www.virtualcitysystems.de/en/).
