### ISSUE TITLE
CityGML4j _ window and door

### ISSUE THREAD

**Issue by sonador3255** [citygml4j/citygml4j#2]
Hi .I want to add window and door in java program sample "BuildingCreator.java", but I don't know how do it?
thanks for your attention

**Comment by clausnagel** [comment]
This is quite simple. The citygml4j object model closely follows the XML encoding of CityGML. So the [CityGML XML schemas](http://schemas.opengis.net/citygml/) and the [CityGML specification document](http://www.opengeospatial.org/standards/citygml) are of help.

Check out the following CityGML snippet of a building having a wall surface and a door. To keep it simple, I have omitted any spatial or thematic properties. 

```xml
<bldg:Building>
  ...
  <bldg:boundedBy>
    <bldg:WallSurface>
      ...
      <bldg:opening>
        <bldg:Door>
        ...
        </bldg:Door>
      </bldg:opening>
    </bldg:WallSurface>
  </bldg:boundedBy>
</bldg:Building>
```

Note that the ```Door``` feature is connected to the ```WallSurface``` through the ```opening``` feature property. Likewise, the ```Building``` feature has a ```boundedBy``` feature property that contains the ```WallSurface```.

Now, simply  build the same hierarchy with citygml4j objects.

```java
// create building, wall surface and door
Building building = new Building();
WallSurface wallSurface = new WallSurface();
Door door = new Door();
		
// add door to wall surface through an opening property
OpeningProperty opening = new OpeningProperty(door);
wallSurface.addOpening(opening);

// add wall surface to building through boundedBy property
BoundarySurfaceProperty boundedBy = new BoundarySurfaceProperty(wallSurface);
building.addBoundedBySurface(boundedBy);
```

Finally, add some geometry and attributes. The ```BuildingCreator.java``` contains sample code for this.

When trying this example, be careful to import all classes from the ```org.citygml4j.model.citygml.building``` package, which maps the contents of the _CityGML Building_ module. For instance, there is also a ```WallSurface``` in the _Bridge_ and _Tunnel_ modules, both of which are mapped to separate Java packages. This package structure follows the conceptual CityGML UML model.

**Comment by sonador3255** [comment]
Dear clausnagel ,
Thank you for your help. Iused your witting code in program sample "BuildingCreator.java", and I changed the file as follow:
In the main: 

                boundedBy.add(createBoundarySurface(CityGMLClass.BUILDING_ROOF_SURFACE, roof_1));
                boundedBy.add(createBoundarySurface(CityGMLClass.BUILDING_ROOF_SURFACE, roof_2));
                boundedBy.add(createBoundaryFeatureOfSurface(CityGMLClass.BUILDING_DOOR, door,wall_1));
                building.setBoundedBySurface(boundedBy);


And create follow function:

                private BoundarySurfaceProperty createBoundaryFeatureOfSurface(CityGMLClass type, Polygon geometry1,Polygon geometry2){
                     AbstractBoundarySurface boundarySurface = null;
                     WallSurface wallSurface = new WallSurface();
                     OpeningProperty opening;
                     switch (type) {
                         case BUILDING_DOOR:
                                Door door = new Door();
                
                opening = new OpeningProperty(door);
                wallSurface.addOpening(opening);
                boundarySurface = wallSurface;
                break;
         case BUILDING_WINDOW:
             //WallSurface wallSurface = new WallSurface();
                Window window = new Window();
               
                opening = new OpeningProperty(window);
                wallSurface.addOpening(opening);
                boundarySurface = wallSurface;
             break;
         default :
             break;
     }
      if (boundarySurface != null) {
            boundarySurface.setLod3MultiSurface(new MultiSurfaceProperty(new MultiSurface(geometry1,geometry2)));
            return new BoundarySurfaceProperty(boundarySurface);
        }           
        return null; 
     }
but the door geometry didn't create when I open file in viewer?

**Comment by clausnagel** [comment]
Well, obviously you do not assign geometry to the ```Door``` feature in your code... Use, for instance, the ```setLod3MultiSurface(...)``` method on the ```Door``` object.

**Comment by sonador3255** [comment]
I use   setLod3MultiSurface(...)  in following code with change:

            if (boundarySurface != null) {
                    boundarySurface.setLod3MultiSurface(new MultiSurfaceProperty(new MultiSurface(geometry1,geometry2)));
                    return new BoundarySurfaceProperty(boundarySurface);
                }

Isn't it right?

**Comment by clausnagel** [comment]
But you assign the geometry only to the ```boundarySurface``` and not to the ```door```. Both need geometry.

**Comment by clausnagel** [comment]
Please check out the official CityGML example at http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD3-EPSG25832.gml

It demonstrates the use of openings and how to assign geometry. The XML structure helps to understand which citygml4j objects to create. Feel free to re-open if you have further questions.
