### ISSUE TITLE
CityModelWriter does not write CityModel ADE

### ISSUE THREAD

**Issue by betzms** [citygml4j/citygml4j#28]
It is not possible to write the ADE of CityModels with the CityModelWriter.

https://gist.github.com/betzms/598a88aaca65289c73586629899d5f29

Example file here:
[TestOutput.zip](https://github.com/citygml4j/citygml4j/files/5715287/TestOutput.zip)

The reason it works with the CityGMLWriter but not the CityModelWriter is that to write the end tag of CityModel the CityModelWriter uses a SAXFragmentWriter with the mode TAIL, which only writes end tags. But for writing the ADEs it would need to also write start tags and content.

I think it should be possible to write ADE with the CityModelWriter as well?

**Comment by clausnagel** [comment]
Hi @betzms, please us a [`CityModelInfo`](https://github.com/citygml4j/citygml4j/blob/master/src/main/java/org/citygml4j/xml/io/writer/CityModelInfo.java) object for this purpose. You can assign CityModel-specific properties to this object including ADE properties.

Once you have populated your `CityModelInfo` object, simply use the `setCityModelInfo` method of `CityModelWriter` to assign it to the writer. This must be done _before_ calling `writeStartDocument` or writing the first feature member using `writeFeatureMember`. The writer should then write your ADE properties.

Hope this helps.

**Comment by betzms** [comment]
Thanks for the fast response.

That is why I have

`			writer.setSchemaLocations(CityGMLVersion.DEFAULT);
			writer.setCityModelInfo(new CityModelInfo(cityModel));
`

In line 20-21

**Comment by clausnagel** [comment]
Ok, sorry, did not inspect your code carefully enough. Will test with a local ADE and let you know my results. If you can share your ADE extension, then we could work on the same test dataset.

**Comment by betzms** [comment]
You don't actually need the extension. It will simply not be unmarshalled, but it will be kept as generic elements which is enough. It works with the GMLWriter just not with the CityModelWriter.

It should still write the ADE even if one does not have the extension I think.

Nevertheless here is the development version. 
[citygml4j-quality-ade-0.0.1-SNAPSHOT.jar.zip](https://github.com/citygml4j/citygml4j/files/5718084/citygml4j-quality-ade-0.0.1-SNAPSHOT.jar.zip)

**Comment by clausnagel** [comment]
Thanks @betzms, bug confirmed. Will let you know when it is resolved.

**Comment by clausnagel** [comment]
fixed with 264bcd852246b4b6a2689e621f8b46266bc15ba0

**Comment by clausnagel** [comment]
Closing this issue. Bug fix has been released with version 2.11.2.
