### ISSUE TITLE
v3.0.0-rc.2: AbstractGenericAttribute as Template

### ISSUE THREAD

**Issue by b-schwab** [citygml4j/citygml4j#29]
Hi @clausnagel, thanks for the great library!

I'm currently upgrading [rtron](https://github.com/tum-gis/rtron) to RC2 of version 3. Often I keep a list of different attributes, which  works very well with `List<AbstractGenericAttribute>` in v.2.11.2. With the template implementation in v3.0.0 RC2 the handling becomes a little bit more difficult, since `T` can take any type at `List<AbstractGenericAttribute<T>>` (not just the CityGML attribute types). What is your opinion on this?

I can certainly resolve the situation alternatively, however I wanted to provide some feedback.

**Comment by clausnagel** [comment]
Thanks for your feedback, @b-schwab. And congrats to rtron, really cool work.

Do you mind sharing a snippet of your code to demonstrate the issue? I think using `List<AbstractGenericAttribute<?>>` instead should already solve the problem, but this is just guessing.

In general, it should be possible to not define `AbstractGenericAttribute` as generic type. I think it saved me some lines of code this way, but if it's easier to use the API without the generic type I'm also fine.

**Comment by b-schwab** [comment]
Thanks for the quick reply, @clausnagel !

Your hint about using generic types also solved my case very well: I have an [intermediary implementation](https://github.com/tum-gis/rtron/blob/3b156e6450315110bd608afcf1e6e4d025661b99/rtron-model/src/main/kotlin/io/rtron/model/roadspaces/roadspace/attribute/Attributes.kt#L24) of attributes which also contains [attibute lists](https://github.com/tum-gis/rtron/blob/3b156e6450315110bd608afcf1e6e4d025661b99/rtron-model/src/main/kotlin/io/rtron/model/roadspaces/roadspace/attribute/Attributes.kt#L94). Afterwards, the intermediary attributes are [mapped](https://github.com/tum-gis/rtron/blob/3b156e6450315110bd608afcf1e6e4d025661b99/rtron-transformer/src/main/kotlin/io/rtron/transformer/roadspace2citygml/transformer/AttributesAdder.kt#L77) onto the citygml4j v.3 representation with an option for flattening out lists. Interestingly, the example also shows the origin of my comment, since I used [sealed classes](https://www.baeldung.com/kotlin/sealed-classes) to restrict the subclasses. So from my side, there is no reason to make adjustments!

The writing (and mappings) of different CityGML versions works very well, as far as I can tell. Really great work!! However, I noticed that `lod0Point` of `AbstractSpace` are not represented when writing CityGML2 (e.g. CityFurniture, GenericCityObject) . This is especially relevant for traffic signs and traffic lights, since they are represented as point geometries in OpenDRIVE. What is the best way to handle this with citygml4j v.3? In my case, switching between writing CityGML2 and 3 is quite important until the 3dcitydb and FME fully support CityGML3.

**Comment by clausnagel** [comment]
Well, `GenericCityObject` does have an LOD 0 representation in CityGML 2.0. So the `lod0Point` should be mapped automatically. This sounds like a bug, and I will check what is going on here.

`CityFurniture`, on the other hand, does not have an LOD 0 representation in CityGML. So how should an `lod0Point` be automatically mapped? I wonder how you store this point representation in the current version of rtron that only supports CityGML 2.0?

**Comment by b-schwab** [comment]
Thanks! I created a [simple example](https://github.com/b-schwab/citygml4j/blob/bc2920fdd8ad42e183c3060124c7e09725ff64b0/citygml4j-samples/src/main/java/processing_citygml/CreatingGenericOccupiedSpace.java#L61) for mapping a `lod0Point` of `GenericOccupiedSpace` (CityGML3) to `lod0Geometry` of `GenericCityObject` (CityGML2). Furthermore, I was able to solve the mapping problem by extending the [default geometry writing function](https://github.com/b-schwab/citygml4j/blob/bc2920fdd8ad42e183c3060124c7e09725ff64b0/src/main/java/org/citygml4j/xml/adapter/CityGMLSerializerHelper.java#L174) in the CityGMLSerializerHelper (if it helps, I could also create a PR).

Regarding `CityFurniture`, rtron is bending the definitions of CityGML2 and currently assigns the point representation of traffic signs and lights to `lod1Geometry`. However, in the long term I wanted to implement the use of implicit geometries for this anyhow. That would probably be the better option instead of trying to map geometries between different LoDs.

Thank you for your comments!

**Comment by clausnagel** [comment]
Thanks, and yes, please issue a PR :-) Your bugfix looks good.

Implicit geometries are also associated with LODs in CityGML, and `CityFurniture` unfortunately does neither provide an LOD0 implicit geometry in CityGML 2.0.

**Comment by clausnagel** [comment]
`lod0Point` bug fixed with #30. Thanks for the PR, @b-schwab

**Comment by b-schwab** [comment]
Great! I'm pleased when I can contribute to this library :)

So, I implemented the usage of implicit geometries at LoD2 to represent traffic signs and lights. Thanks to the well-functioning mappings of citygml4j v3.0.0-rc.2, rtron can now be [configured](https://github.com/tum-gis/rtron/blob/4e5c386ca9b4195dfe3c768245c2194b14c9f7c6/rtron-main/src/main/resources/configurations/complete-sample.kts#L46) to write CityGML2, CityGML3, or both (separate files, but in one rtron run).

I think, we can now close this issue as resolved. Many thanks again!
