### ISSUE TITLE
insert SrsName attribute in envelope tag

### ISSUE THREAD

**Issue by sonador3255** [citygml4j/citygml4j#3]
Hello 

 Building building = new Building();    
 BoundingShape boundedBy1 = building.calcBoundedBy(false);
 boundedBy1.getEnvelope().setSrsName("urn:ogc:def:crs,crs:EPSG:6.12:31466,crs:EPSG:6.12:5783");

I wrote The above code in my program to insert the srsName attribute  in envelope tag in my citygml file but i find this error in my program,

[11:18:05] setting up citygml4j context and JAXB builder
[11:18:10] creating LOD2 building as citygml4j in-memory object tree
Exception in thread "main" java.lang.NullPointerException
	at createbuildingfromosm1.CreateBuildingFromOSM1.doMain(CreateBuildingFromOSM1.java:101)
	at createbuildingfromosm1.CreateBuildingFromOSM1.main(CreateBuildingFromOSM1.java:78)
Java Result: 1
BUILD SUCCESSFUL (total time: 6 seconds)

,please guide me

**Comment by clausnagel** [comment]
Your ```Building``` instance has no geometry. The ```calcBoundedBy``` method returns ```null``` as result in such cases instead of some default or initial value such as (0,0,0) for both the lower and upper corner of the envelope. So you have to check for ```null``` otherwise you run into a NPE as in your example.

**Comment by clausnagel** [comment]
Closing this issue. If you want to assign a ```gml:Envelope``` to a newly created ```Building``` object without geometry, then do not use ```calcBoundedBy``` but create the ```gml:Envelope``` object yourself.

```java
Building building = new Building();
Envelope envelope = new Envelope();
envelope.setSrsName("urn:ogc:def:crs,crs:EPSG:6.12:31466,crs:EPSG:6.12:5783");
		
// set lower and upper corner
envelope.setLowerCorner(...);
envelope.setUpperCorner(...);
		
// assign envelope to building
building.setBoundedBy(new BoundingShape(envelope));
```
