### ISSUE TITLE
CityGML Geometry of Window

### ISSUE THREAD

**Issue by sonador3255** [citygml4j/citygml4j#4]
Hello ,
i read a sample gml for building with window:
  <bldg:boundedBy> 
  <bldg:WallSurface> 
  …
  <bldg:lod3MultiSurface>
   <gml:MultiSurface> 
  <gml:surfaceMember> 
  <gml:CompositeSurface gml:id="GML_1d350a50-6acc-4d3c-8c28-326ca4305fd1"> 
  <gml:surfaceMember> 
  <gml:Polygon gml:id="PolyID10204_1916_571790_369478">
  </gml:Polygon>
   </gml:surfaceMember> 
  <gml:surfaceMember> 
  <gml:Polygon gml:id="PolyID10205_105_876837_53833"> 
  <gml:exterior>
   …
  </gml:exterior> 
  <gml:interior> 
  …
  </gml:interior> 
  <gml:interior>
   …
   </gml:interior>
   </gml:Polygon> 
  </gml:surfaceMember> 
  <gml:surfaceMember>
  </gml:CompositeSurface>

I want to add window to a wall of my sample building . which function of citygml4j can to set geometry of interior ring of wall(the geometry of window). and which function of citygml4j set exterior ring for wall in CompositeSurface tag?

**Comment by sonador3255** [comment]
I wrote this code:
wall_2.addInterior(window.getExterior());

but i see the result
![untitled](https://cloud.githubusercontent.com/assets/11032412/11031556/9dc7f1dc-86ea-11e5-8a2d-15202d2e6892.png)

**Comment by sonador3255** [comment]
please help me!

**Comment by clausnagel** [comment]
It's hard to guess your issue from the information provided.

According to the CityGML specification, the geometry of a wall surface must have a hole, which is then filled by the geometry of the window. Geometrically, this can, for instance, be realized by modelling the wall geometry as ```gml:Polygon``` having a ```gml:exterior``` ring and a ```gml:interior``` ring denoting the hole. The geometry of the window can then be given as ```gml:Polygon``` having a ```gml:exterior``` ring which fits into the interior ring of the wall. Note that per GML 3.1.1 definition, the orientation of an interior ring is reversed compared to the exterior ring. This might be a problem in your code example.

citygml4j provides the ```setExterior()``` and ```addInterior()``` methods on ```org.citygml4j.model.gml.geometry.primitives.Polygon``` to implement the above scenario.

If you attach your CityGML file and citygml4j code, it might be easier to understand your problem.

Cheers,
Claus

**Comment by sonador3255** [comment]
these are may Citygmlcode file and outputgml file.  
[MyCode.txt](https://github.com/citygml4j/citygml4j/files/53132/MyCode.txt)
[OutputGML.txt](https://github.com/citygml4j/citygml4j/files/53134/OutputGML.txt)


I thank you for helping me

**Comment by sonador3255** [comment]
[MyCode.txt](https://github.com/citygml4j/citygml4j/files/53573/MyCode.txt)
[Uploading OutputGML.txt…]()
please help me!

**Comment by sonador3255** [comment]
I write this code:
Polygon ground = geom.createLinearPolygon(new double[] {uper,0,0, 0,12,0, 6,12,0, 6,0,0, 0,0,0}, 3);
		Polygon wall_1 = geom.createLinearPolygon(new double[] {6,0,0, 6,12,0, 6,12,6, 6,0,6, 6,0,0}, 3);
                
		Polygon wall_2e = geom.createLinearPolygon(new double[] {0,0,0, 0,0,6, 0,12,6, 0,12,0, 0,0,0}, 3);
		Polygon wall_3 = geom.createLinearPolygon(new double[] {0,0,0, 6,0,0, 6,0,6, 3,0,9, 0,0,6, 0,0,0}, 3);
		Polygon wall_4 = geom.createLinearPolygon(new double[] {6,12,0, 0,12,0, 0,12,6, 3,12,9, 6,12,6, 6,12,0}, 3);
		Polygon roof_1 = geom.createLinearPolygon(new double[] {6,0,6, 6,12,6, 3,12,9, 3,0,9, 6,0,6}, 3);
		Polygon roof_2 = geom.createLinearPolygon(new double[] {0,0,6, 3,0,9, 3,12,9, 0,12,6, 0,0,6}, 3);
                
               Polygon window = geom.createLinearPolygon(new double[] {0,1,1, 0,1,5, 0,10,5, 0,10,1, 0,1,1}, 3);
               Polygon wall_2in=window;
               Polygon wall_2=new Polygon();
               wall_2.setExterior(wall_2e.getExterior());
               wall_2.addInterior(wall_2in.getExterior());

but I don't know what is wrong?

**Comment by clausnagel** [comment]
Please find below a simple code example to create a wall surface containing a window. 

```java
public class WindowTest {
	
	public static void main(String[] args) throws Exception {
		CityGMLContext ctx = new CityGMLContext();
		CityGMLBuilder builder = ctx.createCityGMLBuilder();
		GMLGeometryFactory geom = new GMLGeometryFactory();

		// step 1: create wall and window objects and assign geometry
		
		// 1.1 create wall surface object and assign geometry
		WallSurface wallSurface = new WallSurface();
		Polygon wallPolygon = geom.createLinearPolygon(new double[] {0,0,0, 0,0,6, 0,12,6, 0,12,0, 0,0,0}, 3);
		wallSurface.setLod3MultiSurface(new MultiSurfaceProperty(new MultiSurface(wallPolygon)));

		// 1.2 create window object and assign geometry
		Window window = new Window();
		Polygon windowPolygon = geom.createLinearPolygon(new double[] {0,1,1, 0,1,5, 0,10,5, 0,10,1, 0,1,1}, 3);
		window.setLod3MultiSurface(new MultiSurfaceProperty(new MultiSurface(windowPolygon)));

		// 1.3 assign window to wall surface
		wallSurface.addOpening(new OpeningProperty(window));

		// step 2: in addition, we also need to cut a hole into the wall surface geometry.
		// in this example, the hole is represented as interior ring of the wall surface polygon.
		// note that according to GML3 the points of an interior ring have to be given in reverse order. 
		// since the window should seal the hole in the wall, we simply take the points from the
		// window polygon. for more information, check pp. 69 of the CityGML 2.0 specification.
		
		// 2.1 get exterior ring of window geometry
		LinearRing exteriorRing = (LinearRing)windowPolygon.getExterior().getRing();

		// 2.2 the toList3d(boolean reverse) method retrieves the point list and reverses the point order if requested
		// note that you could also implement your own methods to reverse point lists... 
		List<Double> pointList = exteriorRing.toList3d(true);

		// 2.3 assign the point list as interior ring to the wall surface polygon
		LinearRing interiorRing = new LinearRing();
		interiorRing.setPosList(geom.createDirectPositionList(pointList, 3));
		wallPolygon.addInterior(new Interior(interiorRing));

		// voilá. the rest of the code is just to write an test file that
		// can be loaded and viewed with a CityGML viewer.
		Building building = new Building();
		building.addBoundedBySurface(new BoundarySurfaceProperty(wallSurface));

		CityGMLOutputFactory out = builder.createCityGMLOutputFactory(CityGMLVersion.DEFAULT);
		CityGMLWriter writer = out.createCityGMLWriter(new File("output.gml"));
		writer.setPrefixes(CityGMLVersion.DEFAULT);
		writer.setSchemaLocations(CityGMLVersion.DEFAULT);
		writer.setIndentString("  ");
		writer.write(building);
		writer.close();	
	}
}
```

**Comment by sonador3255** [comment]
Thank you very much,  dear Clausnagel.
