### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by strech345** [citygml4j/citygml4j#5]
Hello,

is it possible to simplyfy the geometry with this example? https://github.com/citygml4j/citygml4j/blob/master/samples/processing_citygml/simple_spatial_filter/src/SimpleSpatialFilter.java

I've downloaded the lod2 of Berlin, but i think it's to much too show it in 3dcitydb-web-map. So i think it's a good idea too simplify the geometry.

**Comment by strech345** [comment]
nevermind 
i simplify it in 3dcitydb importer exporter
Queries.java -> BUILDING_PART_FOOTPRINT_LOD2 
SELECT ST_Simplify(sg.geometry,1)

**Comment by rchr** [comment]
Hello stretch345,

what do you exactly mean with simplifying the geometry?

The [example] (https://github.com/citygml4j/citygml4j/blob/master/samples/processing_citygml/simple_spatial_filter/src/SimpleSpatialFilter.java) shows the usage of a spatial filter. In this case it cuts out a certain area of the city model using a bounding box. It will not change the geometries located in the bounding box. 

If you really want to simplify the geometry by the [Douglas–Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) you can use the [ST_Simplify](http://postgis.net/docs/manual-2.2/ST_Simplify.html) function of PostGIS (as you already found out). It will return a 'simplified' version of the geometry, which means it reduces the number of points of a curve. This will possibly change your geometries.

**Comment by strech345** [comment]
Hello rchr,
Thanks,
yes, like i write in my last post i use the St_Simplify in 3DCityDB for exporting my model with simplify polygons.
