### ISSUE TITLE
Line numbers not available for debugging purposes

### ISSUE THREAD

**Issue by jsimomaa** [citygml4j/citygml4j#6]
Started using citygml4j library today and found out that the ant target `compile_src` compiles the source code without the `debug="on"` flag. This makes it impossible to debug the execution of the code with a debugger.

I compiled the library on my own and added the `debug="on"` flag for both `javac` commands and got the line numbers and debugging to work. Although it would be nice to just rely on the latest version fetched with Maven and the debugging would work out of the box.

citygml4j-2.4.0.jar **with** `debug="on"` 2 982 833  bytes
citygml4j-2.4.0.jar **without** `debug="on"` 2 407 112  bytes

Is this a deliberate decision? Thanks :+1:

**Comment by clausnagel** [comment]
Thank's for pointing out. Debug information is now generated by```compile_src``` for the citygml4j library (9ff3e31b062ff6ebc9552807855431ed2839b65a). Will be available as Maven artifact with the next release.
