### ISSUE TITLE
from KMZ to CityGML?

### ISSUE THREAD

**Issue by Abelon38** [citygml4j/citygml4j#7]
Hi there!

I hope your are doing greate guys! I am trying to find a solution to create CityGML buildings, surfaces files in KMZ to be imported into 3Dcitydb. 
I was recomended by Zinhang this software and I just installed, but I dont know how it works. How can I for exemple comvert KML/KMZ files created with SketchUP to CityGML ? Do you have some videos, documentation, etc?

Thanks for your dedication!
Abel Gonzalez

**Comment by clausnagel** [comment]
citygml4j is a software library but not a ready-to-use KML-to-CityGML converter. You can definitely develop such a conversion tool using citygml4j for the CityGML-related parts. But still you have to write some piece of code.

Cheers,
Claus

**Comment by Abelon38** [comment]
Hi Claus!

Thank you for your respond! I am considering to try the Sketchup plugin CityEditor. Do you have any consideration about this plugin?

Regards,
Abel

**Comment by clausnagel** [comment]
I think there are many alternatives for what you want to do, and CityEditor seems to be one of them. Closing this issue, feel free to re-open if you have additional questions about citygml4j.
