### ISSUE TITLE
CityJSON with "transform" ignored when converting to CityGML

### ISSUE THREAD

**Issue by hugoledoux** [citygml4j/citygml4j#9]
Trying different conversions, and it seems you ignore the "transform", or do I need to activate it somehow?

I'm using the `CityJSONConverter.java` sample code basically.

Otherwise: it is great 😍

**Comment by clausnagel** [comment]
Thanks for your feedback. Well, "transform" should be considered and automatically applied to the "vertices" when reading the CityJSON file. Can you share an example file for testing?

**Comment by hugoledoux** [comment]
one of you example converter to cityjson, then compressed, both files there:
https://www.dropbox.com/sh/ir05uu7fo1ayqwm/AADe2339DoRvJliHsR50CvS8a?dl=0

**Comment by clausnagel** [comment]
Thanks for the test files. Fixed in ac030ea4f315db27e689d2cc468bae77692bec58.
